export const DOGS = [
  {
    id: 0,
    name: "Henny",
    image: "/assets/images/react-lake.jpg",
    breed: "Golden Retriever",
    size: "Large",
    color: "Brown",
    age: 1.5,
    featured: false,
    description: "High Energy, Speed, Thinks he's a Lap Dog",
  },
  {
    id: 1,
    name: "Luna",
    image: "/assets/images/chrome-river.jpg",
    breed: "",
    age: 0.8,
    size: "Small",
    color: "White",
    featured: false,
    description: "Chill, Has a Sibling Rivalry with Pepper",
  },
  {
    id: 2,
    name: "Pepper",
    image: "/assets/images/breadcrumb-trail.jpg",
    breed: "",
    age: 0.8,
    size: "Small",
    color: "Black",
    featured: false,
    description: "Thinks she's a Bear",
  },
  {
    id: 3,
    name: "Kiera",
    image: "/assets/images/redux-woods.jpg",
    breed: "",
    age: 3,
    size: "Medium",
    color: "Varies",
    featured: true,
    description: "Good doggo, well mannered and well trained",
  },
];
